name: iz_show_time_tracker
description: A cross-platform mobile app to track films and TV shows with smart notifications.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^22.3.0
  workmanager: ^0.10.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/IzShowTimeIcon.png
  web:
    generate: true
    image_path: assets/icons/IzShowTimeIcon.png
    background_color: "#FFD700"
    theme_color: "#FFD700"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
